### ISSUE TITLE
PIZ fails for images with zero regions

### ISSUE THREAD

**Issue by harskish** [syoyo/tinyexr#100]
Reading PIZ-compressed images works incorrectly if they contain large regions of zeros. The output will contain large horizontal strips of zeros. The bug happens with 3-channel RGB images as well as single channel scalar images.

OpenEXR seems to load the images fine. Tested with mrViewer v4.3.5 64bit.

I've pushed code and images to demonstrate the issue into my fork of the repo:
https://github.com/harskish/tinyexr/commit/5a2db2dcf6ca0973d6b57584c75c7b439491e6b7

The most simple case where loading fails is a scalar (1x35) black image with the final pixel set to one. This image is included as `piz_bug/broken_images/broken_tiny_1d.exr`.

**Comment by syoyo** [comment]
Thank you for reporting an issue.

The reason is this : 

https://github.com/syoyo/tinyexr/blob/master/tinyexr.h#L8842

Replacing that line with

```
if ((out - 1) < ob) return false;
```

at least decodes all your borken images well.

I have added this extra check since fuzzer found a out-of-bounds access in OpenEXR's original `getCode` macros. https://github.com/syoyo/tinyexr/issues/78

I thinks it should be safe to accept

```
if ((out - 1) < ob) return false;
```

but need some more testing(and do regression test with issue 78 test case)

**Comment by syoyo** [comment]
```
if ((out - 1) < ob) return false;
```

I have confirmed issue 78 regression passes with the above bounds check equation, also added regression test with your PIZ data. All test passes so I have pushed the change in this commit: https://github.com/syoyo/tinyexr/commit/adad570ab8be2d42389a3520011e2c6a6ad8af43

**Comment by harskish** [comment]
Awesome, thanks for fixing this so quickly!
