### ISSUE TITLE
PIZ compression support ?

### ISSUE THREAD

**Issue by gjaegy** [syoyo/tinyexr#17]
I have integrated your library which seems to be great, and very easy to integrate.
No luck, all the .exr files sent by our artist are using the PIZ compression scheme, and therefore not supported by the loader :(
Is there any plan to add support for this compression scheme ?

Thanks a lot for your great work BTW !

**Comment by syoyo** [comment]
I am planning to add zstd compression support #16 but not PIZ for now.

I'm a bit worried about patent infringement. Some of compressions(at least recent lossy compressor contributed by DreamWorks to EXR2.0) doesn't allow using it outside of OpenEXR source code.

Anyway, PIZ may be OK since its inherently Wavelet algorithm. 

PR is always welcome BTW!

**Comment by syoyo** [comment]
https://github.com/syoyo/tinyexr/commit/40deb4e81feff1cf4e708f65cb254b9634f3a5c8

Added initial support of loading PIZ compression. You can try it!

**Comment by gjaegy** [comment]
Thanks for that ! I am in vacation right now but will check and test as soon as I am back in the office !
Cheers
Greg
Le 8 août 2015 4:35 PM, Syoyo Fujita <notifications@github.com> a écrit :40deb4e

Added initial support of loading PIZ compression. You can try it!

**Comment by syoyo** [comment]
https://github.com/syoyo/tinyexr/commit/4b555bbbebd9fa1b2c0937a3af08d98831f58ebb

PIZ decode/encode supported.
